# Generated by Django 2.2.5 on 2019-09-10 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="date_posed",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="date_published",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(),
        ),
    ]
