# Generated by Django 2.2.5 on 2019-09-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_auto_20190910_0410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="date_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
