# Generated by Django 2.2.5 on 2019-09-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190910_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_author',
            new_name='asker',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_posed',
            new_name='date_asked',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
