# Generated by Django 2.2.5 on 2019-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_auto_20190910_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_text",
            field=models.TextField(blank=True),
        ),
    ]
