# Generated by Django 2.2.5 on 2019-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="question_1",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="submission",
            name="question_2",
            field=models.CharField(max_length=200),
        ),
    ]
