# Generated by Django 2.2.5 on 2019-09-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0009_auto_20190911_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
