# Generated by Django 2.2.5 on 2019-09-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_question_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="q1_is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="q2_is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
