# Generated by Django 2.2.5 on 2019-09-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_auto_20190917_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
