# Generated by Django 2.2.5 on 2019-09-24 00:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0014_auto_20190917_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_video",
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
