# Generated by Django 5.1.4 on 2025-01-17 13:57

from django.db import migrations, connection


def check_and_fix_embed_video_column(apps, schema_editor):
    """
    Check if the answer_video_embed column exists and fix it if needed.
    This handles the case where the column might not exist in production.
    """
    with connection.cursor() as cursor:
        # Check if the column exists
        cursor.execute("""
            SELECT column_name, is_nullable
            FROM information_schema.columns
            WHERE table_name = 'questions_question'
            AND column_name = 'answer_video_embed'
        """)

        result = cursor.fetchone()

        if result:
            # Column exists, check if it's nullable
            column_name, is_nullable = result
            if is_nullable == "NO":
                # Column exists but is NOT NULL, so we need to make it nullable
                cursor.execute("""
                    ALTER TABLE questions_question 
                    ALTER COLUMN answer_video_embed DROP NOT NULL
                """)
                print("Made answer_video_embed column nullable")
            else:
                print("answer_video_embed column already nullable")
        else:
            # Column doesn't exist - this is fine, the EmbedVideoField will handle it
            print("answer_video_embed column doesn't exist - no action needed")


def reverse_check_and_fix_embed_video_column(apps, schema_editor):
    """
    Reverse the operation - make the column NOT NULL if it exists.
    """
    with connection.cursor() as cursor:
        # Check if the column exists
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'questions_question'
            AND column_name = 'answer_video_embed'
        """)

        if cursor.fetchone():
            # Column exists, make it NOT NULL
            cursor.execute("""
                ALTER TABLE questions_question 
                ALTER COLUMN answer_video_embed SET NOT NULL
            """)


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0017_alter_submission_question_1"),
    ]

    operations = [
        migrations.RunPython(
            check_and_fix_embed_video_column,
            reverse_check_and_fix_embed_video_column,
        ),
    ]
