# Generated by Django 5.1.4 on 2025-01-17 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0017_alter_submission_question_1"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE questions_question ALTER COLUMN answer_video_embed DROP NOT NULL;",
            reverse_sql="ALTER TABLE questions_question ALTER COLUMN answer_video_embed SET NOT NULL;",
        ),
    ]
